language: python
python:
  - "3.6"
  - "3.7"

# set up the image with system requirements
addons:
  apt:
    update: true
    packages: zsh

# do the install
install:
  - ./setup.zsh -a

# check all branches
branches:
  only:
  - gh-pages
  - /.*/
