language: python
sudo: required
dist: xenial
python: "3.7"

# set up the image with system requirements
addons:
  apt:
    update: true
    packages:
      - zsh
      - unzip

# do the install, but only almost all because otherwise it takes hours
install:
  - ./setup.zsh -A
  - pip install hypothesis pytest
# check all branches
branches:
  only:
#    - gh-pages
    - /.*/

# skip tests for now
script:
  - pytest
