language: python
python:
  - "3.6"

# hack to make ptyhon 3.7 work -_-
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# set up the image with system requirements
addons:
  apt:
    update: true
    packages:
      - zsh
      - unzip

# do the install, but only almost all because otherwise it takes hours
install:
  - ./setup.zsh -A

# check all branches
branches:
  only:
  - gh-pages
  - /.*/
