language: python
python:
  - "3.6"

# set up the image with system requirements
addons:
  apt:
    update: true
    packages:
      - zsh
      - unzip

# do the install, but only almost all because otherwise it takes hours
install:
  - ./setup.zsh -A

# check all branches
branches:
  only:
#    - gh-pages
    - /.*/

# skip tests for now
script:
  - pytest
